spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.34.252.45:3306/mr_moss
    username: root
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true